# Site wide configuration
title:            Conception participative de tableaux de bord d’apprentissage
locale:           fr_FR
theme: jekyll-theme-slate

nav_pages:
  - blog/index.md
  - index.html
  - talks.md
  - about.md
  - contact.md

footer_pages:
  - books-for-geeks.html
  - fine-print.md
